version: "3.8"

services:
  app:
    build: .
    container_name: auxsol-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auxsol
      - DIRECT_URL=postgresql://postgres:postgres@db:5432/auxsol
      - NEXTAUTH_URL=http://18.233.8.152:3000
      - AUTH_TRUST_HOST=true
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             node server.js"

  db:
    image: postgres:15-alpine
    container_name: auxsol-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auxsol
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: